### ISSUE TITLE
Not working for ASIS_A

### ISSUE THREAD

**Issue by understorey** [goergen95/wapoR#1]
`collection = "ASIS"
product = "ASI_A" # product code
rbind(c(-20,45),c(30,73)) %>% 
  as.data.frame %>% 
  sf::st_as_sf(coords = c(1,2))->window #EU
begin = as.Date("2015-01-01") # begin date is inclusive
end = as.Date("2016-01-01") # end date is exclusive
dimensions = list(SEASON = c("S1", "S2"))
wapor_queryRaster(collection = collection,
                  product = product,
                  dimensions = dimensions,
                  aoi = window,
                  begin = begin,
                  end = end, 
                  APIkey = APIkey, 
                  outdir = ".", 
                  cutline = T, 
                  tiled = F, 
                  compressed = F, 
                  overviews = TRUE)`

**Comment by goergen95** [comment]
The `ASI_A` product has an additional dimension called `LAND` with allowed values `C` for cropland and `P` for pasture. Thus supplying `dimensions = list(SEASON = c("S1", "S2"), LAND = c("C", "P")) ` should do the trick and start the download without additional errors.
